    (defun my-gcd (a b)
	  (cond ((eql b 0)a)
			((> b 0) (my-gcd  (first(list b )) (mod a b) ))  
			)    
	  )

(defun is-palindrome (l)
  ( cond  ((eql (length l) 0) nil)
		  ((eql (length l) 1) t)
		  ((and (eql (length l) 2) (eql (first l) (first (last l)))) t)
		  ((eql (first l) (first (last l)))(is-palindrome (butlast (cdr l))))
		  )
  )

(defun intlist (n)
  (let (result)
	(dotimes (i n result)
	  (push (+ i 1) result)
	  )
	)
  )

(defun analyze (l)
  (let (m )
	(dolist (element l m)
	  (cond ((atom element)
			 (push 'atom m))
			((list element)
			 (push 'list m)))
	  )
	)
  )


(defun only-atoms (x)
  (cond ((and (atom (car x)) (>= (length x) 2))  (only-atoms(cdr x)))
		((and (eql (length x) 1) (atom (car x))) t)
		)
  )


(defun only-atoms-iter (l)
  (dotimes (i (length l))
	(cond ((not(atom (nth i l)))
		   (return nil)
		   )
		  ((and(eql (length l) (+ 1 i)) (atom(nth i l)))
		   (return t)
		   )
		  )
	)
  )


(defun quad-roots (a b c)
  (list   (/ (+ (- 0 b) (sqrt (- (* b b) (* 4 (* a c))))) (* 2 a))
		  (/ (- (- 0 b) (sqrt (- (* b b) (* 4 (* a c))))) (* 2 a))
		  )

  )

(defun rotate-from-right (l n)
  (dotimes (i n l)
	(push (car(last l)) l)
	(setf l (butlast l))
	)
  )

(defun odds (l)
  (cond ((null l)nil)
		(t (cons (car l) (odds (cdr(cdr l)))))
		)
  )

(defun odds-iter (l)
  (let ((result nil)
		(i 1))
	(dolist (e l result)
	  (when (oddp i) (setf result (cons e result)))
	  (incf i)
	  )
	(reverse result)
	)
  )
